version: '3.7'

services:
  app:
    env_file:
      - app.env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    image: proyectosegura
    restart: always
    container_name: app
    volumes:
      -  ./app/sistemaSeg:/app
    depends_on:
      - bd
    
  bd:
    image: mariadb
    restart: always
    env_file:
      - bd.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/certs:/tmp
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/sistemaSeg/static:/static
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    
